// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/goph_keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterRequest) Reset() {
	*x = UserRegisterRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRequest) ProtoMessage() {}

func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserAuthorizedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthorizedRequest) Reset() {
	*x = UserAuthorizedRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthorizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthorizedRequest) ProtoMessage() {}

func (x *UserAuthorizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthorizedRequest.ProtoReflect.Descriptor instead.
func (*UserAuthorizedRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthorizedRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserAuthorizedRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorizedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedResponse) Reset() {
	*x = AuthorizedResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedResponse) ProtoMessage() {}

func (x *AuthorizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedResponse.ProtoReflect.Descriptor instead.
func (*AuthorizedResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizedResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SaveRawDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRawDataRequest) Reset() {
	*x = SaveRawDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRawDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRawDataRequest) ProtoMessage() {}

func (x *SaveRawDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRawDataRequest.ProtoReflect.Descriptor instead.
func (*SaveRawDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *SaveRawDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveRawDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SaveRawDataRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SaveLoginWithPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLoginWithPasswordRequest) Reset() {
	*x = SaveLoginWithPasswordRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLoginWithPasswordRequest) ProtoMessage() {}

func (x *SaveLoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*SaveLoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *SaveLoginWithPasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveLoginWithPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SaveLoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SaveLoginWithPasswordRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SaveBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBinaryDataRequest) Reset() {
	*x = SaveBinaryDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBinaryDataRequest) ProtoMessage() {}

func (x *SaveBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*SaveBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *SaveBinaryDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveBinaryDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SaveBinaryDataRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SaveCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Month         string                 `protobuf:"bytes,3,opt,name=Month,proto3" json:"Month,omitempty"`
	Year          string                 `protobuf:"bytes,4,opt,name=Year,proto3" json:"Year,omitempty"`
	CardHolder    string                 `protobuf:"bytes,5,opt,name=CardHolder,proto3" json:"CardHolder,omitempty"`
	Cvv           string                 `protobuf:"bytes,6,opt,name=Cvv,proto3" json:"Cvv,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCardDataRequest) Reset() {
	*x = SaveCardDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCardDataRequest) ProtoMessage() {}

func (x *SaveCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCardDataRequest.ProtoReflect.Descriptor instead.
func (*SaveCardDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *SaveCardDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveCardDataRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *SaveCardDataRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *SaveCardDataRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *SaveCardDataRequest) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *SaveCardDataRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *SaveCardDataRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetRawDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRawDataRequest) Reset() {
	*x = GetRawDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRawDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRawDataRequest) ProtoMessage() {}

func (x *GetRawDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRawDataRequest.ProtoReflect.Descriptor instead.
func (*GetRawDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetRawDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRawDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRawDataResponse) Reset() {
	*x = GetRawDataResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRawDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRawDataResponse) ProtoMessage() {}

func (x *GetRawDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRawDataResponse.ProtoReflect.Descriptor instead.
func (*GetRawDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *GetRawDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetRawDataResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetLoginWithPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginWithPasswordRequest) Reset() {
	*x = GetLoginWithPasswordRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginWithPasswordRequest) ProtoMessage() {}

func (x *GetLoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*GetLoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *GetLoginWithPasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetLoginWithPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginWithPasswordResponse) Reset() {
	*x = GetLoginWithPasswordResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginWithPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginWithPasswordResponse) ProtoMessage() {}

func (x *GetLoginWithPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginWithPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetLoginWithPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *GetLoginWithPasswordResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetLoginWithPasswordResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetLoginWithPasswordResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetBinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryDataRequest) Reset() {
	*x = GetBinaryDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryDataRequest) ProtoMessage() {}

func (x *GetBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*GetBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *GetBinaryDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryDataResponse) Reset() {
	*x = GetBinaryDataResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryDataResponse) ProtoMessage() {}

func (x *GetBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*GetBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *GetBinaryDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBinaryDataResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardDataRequest) Reset() {
	*x = GetCardDataRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardDataRequest) ProtoMessage() {}

func (x *GetCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardDataRequest.ProtoReflect.Descriptor instead.
func (*GetCardDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *GetCardDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Year          string                 `protobuf:"bytes,3,opt,name=Year,proto3" json:"Year,omitempty"`
	CardHolder    string                 `protobuf:"bytes,4,opt,name=CardHolder,proto3" json:"CardHolder,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=Cvv,proto3" json:"Cvv,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardDataResponse) Reset() {
	*x = GetCardDataResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardDataResponse) ProtoMessage() {}

func (x *GetCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardDataResponse.ProtoReflect.Descriptor instead.
func (*GetCardDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *GetCardDataResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetCardDataResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *GetCardDataResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *GetCardDataResponse) GetCardHolder() string {
	if x != nil {
		return x.CardHolder
	}
	return ""
}

func (x *GetCardDataResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *GetCardDataResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetAllSavedDataNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSavedDataNamesRequest) Reset() {
	*x = GetAllSavedDataNamesRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSavedDataNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSavedDataNamesRequest) ProtoMessage() {}

func (x *GetAllSavedDataNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSavedDataNamesRequest.ProtoReflect.Descriptor instead.
func (*GetAllSavedDataNamesRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{16}
}

type GetAllSavedDataNamesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SavedDataNames []string               `protobuf:"bytes,1,rep,name=saved_data_names,json=savedDataNames,proto3" json:"saved_data_names,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllSavedDataNamesResponse) Reset() {
	*x = GetAllSavedDataNamesResponse{}
	mi := &file_proto_goph_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSavedDataNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSavedDataNamesResponse) ProtoMessage() {}

func (x *GetAllSavedDataNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSavedDataNamesResponse.ProtoReflect.Descriptor instead.
func (*GetAllSavedDataNamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllSavedDataNamesResponse) GetSavedDataNames() []string {
	if x != nil {
		return x.SavedDataNames
	}
	return nil
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_proto_goph_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goph_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_proto_goph_keeper_proto_rawDescGZIP(), []int{18}
}

func (x *DelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_goph_keeper_proto protoreflect.FileDescriptor

const file_proto_goph_keeper_proto_rawDesc = "" +
	"\n" +
	"\x17proto/goph_keeper.proto\x12\x06server\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"G\n" +
	"\x13UserRegisterRequest\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"I\n" +
	"\x15UserAuthorizedRequest\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"*\n" +
	"\x12AuthorizedResponse\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"V\n" +
	"\x12SaveRawDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\tR\x04Data\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\"~\n" +
	"\x1cSaveLoginWithPasswordRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Login\x18\x02 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x18\n" +
	"\aComment\x18\x04 \x01(\tR\aComment\"Y\n" +
	"\x15SaveBinaryDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\"\xb7\x01\n" +
	"\x13SaveCardDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Number\x18\x02 \x01(\tR\x06Number\x12\x14\n" +
	"\x05Month\x18\x03 \x01(\tR\x05Month\x12\x12\n" +
	"\x04Year\x18\x04 \x01(\tR\x04Year\x12\x1e\n" +
	"\n" +
	"CardHolder\x18\x05 \x01(\tR\n" +
	"CardHolder\x12\x10\n" +
	"\x03Cvv\x18\x06 \x01(\tR\x03Cvv\x12\x18\n" +
	"\aComment\x18\a \x01(\tR\aComment\"'\n" +
	"\x11GetRawDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"B\n" +
	"\x12GetRawDataResponse\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\x12\x18\n" +
	"\aComment\x18\x02 \x01(\tR\aComment\"1\n" +
	"\x1bGetLoginWithPasswordRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"j\n" +
	"\x1cGetLoginWithPasswordResponse\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\aComment\"*\n" +
	"\x14GetBinaryDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"E\n" +
	"\x15GetBinaryDataResponse\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x18\n" +
	"\aComment\x18\x02 \x01(\tR\aComment\"(\n" +
	"\x12GetCardDataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"\xa3\x01\n" +
	"\x13GetCardDataResponse\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\tR\x06Number\x12\x14\n" +
	"\x05Month\x18\x02 \x01(\tR\x05Month\x12\x12\n" +
	"\x04Year\x18\x03 \x01(\tR\x04Year\x12\x1e\n" +
	"\n" +
	"CardHolder\x18\x04 \x01(\tR\n" +
	"CardHolder\x12\x10\n" +
	"\x03Cvv\x18\x05 \x01(\tR\x03Cvv\x12\x18\n" +
	"\aComment\x18\x06 \x01(\tR\aComment\"\x1d\n" +
	"\x1bGetAllSavedDataNamesRequest\"H\n" +
	"\x1cGetAllSavedDataNamesResponse\x12(\n" +
	"\x10saved_data_names\x18\x01 \x03(\tR\x0esavedDataNames\" \n" +
	"\n" +
	"DelRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name2\xf3\n" +
	"\n" +
	"\vGrpcService\x12E\n" +
	"\n" +
	"CreateUser\x12\x1b.server.UserRegisterRequest\x1a\x1a.server.AuthorizedResponse\x12F\n" +
	"\tLoginUser\x12\x1d.server.UserAuthorizedRequest\x1a\x1a.server.AuthorizedResponse\x12@\n" +
	"\vSaveRawData\x12\x1a.server.SaveRawDataRequest\x1a\x15.server.ErrorResponse\x12T\n" +
	"\x15SaveLoginWithPassword\x12$.server.SaveLoginWithPasswordRequest\x1a\x15.server.ErrorResponse\x12F\n" +
	"\x0eSaveBinaryData\x12\x1d.server.SaveBinaryDataRequest\x1a\x15.server.ErrorResponse\x12B\n" +
	"\fSaveCardData\x12\x1b.server.SaveCardDataRequest\x1a\x15.server.ErrorResponse\x12C\n" +
	"\n" +
	"GetRawData\x12\x19.server.GetRawDataRequest\x1a\x1a.server.GetRawDataResponse\x12a\n" +
	"\x14GetLoginWithPassword\x12#.server.GetLoginWithPasswordRequest\x1a$.server.GetLoginWithPasswordResponse\x12L\n" +
	"\rGetBinaryData\x12\x1c.server.GetBinaryDataRequest\x1a\x1d.server.GetBinaryDataResponse\x12F\n" +
	"\vGetCardData\x12\x1a.server.GetCardDataRequest\x1a\x1b.server.GetCardDataResponse\x12a\n" +
	"\x14GetAllSavedDataNames\x12#.server.GetAllSavedDataNamesRequest\x1a$.server.GetAllSavedDataNamesResponse\x127\n" +
	"\n" +
	"DelRawData\x12\x12.server.DelRequest\x1a\x15.server.ErrorResponse\x12A\n" +
	"\x14DelLoginWithPassword\x12\x12.server.DelRequest\x1a\x15.server.ErrorResponse\x12:\n" +
	"\rDelBinaryData\x12\x12.server.DelRequest\x1a\x15.server.ErrorResponse\x128\n" +
	"\vDelCardData\x12\x12.server.DelRequest\x1a\x15.server.ErrorResponse\x12?\n" +
	"\n" +
	"UpdRawData\x12\x1a.server.SaveRawDataRequest\x1a\x15.server.ErrorResponse\x12S\n" +
	"\x14UpdLoginWithPassword\x12$.server.SaveLoginWithPasswordRequest\x1a\x15.server.ErrorResponse\x12E\n" +
	"\rUpdBinaryData\x12\x1d.server.SaveBinaryDataRequest\x1a\x15.server.ErrorResponse\x12A\n" +
	"\vUpdCardData\x12\x1b.server.SaveCardDataRequest\x1a\x15.server.ErrorResponseB(Z&github.com/developerc/GophKeeper/protob\x06proto3"

var (
	file_proto_goph_keeper_proto_rawDescOnce sync.Once
	file_proto_goph_keeper_proto_rawDescData []byte
)

func file_proto_goph_keeper_proto_rawDescGZIP() []byte {
	file_proto_goph_keeper_proto_rawDescOnce.Do(func() {
		file_proto_goph_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goph_keeper_proto_rawDesc), len(file_proto_goph_keeper_proto_rawDesc)))
	})
	return file_proto_goph_keeper_proto_rawDescData
}

var file_proto_goph_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_goph_keeper_proto_goTypes = []any{
	(*ErrorResponse)(nil),                // 0: server.ErrorResponse
	(*UserRegisterRequest)(nil),          // 1: server.UserRegisterRequest
	(*UserAuthorizedRequest)(nil),        // 2: server.UserAuthorizedRequest
	(*AuthorizedResponse)(nil),           // 3: server.AuthorizedResponse
	(*SaveRawDataRequest)(nil),           // 4: server.SaveRawDataRequest
	(*SaveLoginWithPasswordRequest)(nil), // 5: server.SaveLoginWithPasswordRequest
	(*SaveBinaryDataRequest)(nil),        // 6: server.SaveBinaryDataRequest
	(*SaveCardDataRequest)(nil),          // 7: server.SaveCardDataRequest
	(*GetRawDataRequest)(nil),            // 8: server.GetRawDataRequest
	(*GetRawDataResponse)(nil),           // 9: server.GetRawDataResponse
	(*GetLoginWithPasswordRequest)(nil),  // 10: server.GetLoginWithPasswordRequest
	(*GetLoginWithPasswordResponse)(nil), // 11: server.GetLoginWithPasswordResponse
	(*GetBinaryDataRequest)(nil),         // 12: server.GetBinaryDataRequest
	(*GetBinaryDataResponse)(nil),        // 13: server.GetBinaryDataResponse
	(*GetCardDataRequest)(nil),           // 14: server.GetCardDataRequest
	(*GetCardDataResponse)(nil),          // 15: server.GetCardDataResponse
	(*GetAllSavedDataNamesRequest)(nil),  // 16: server.GetAllSavedDataNamesRequest
	(*GetAllSavedDataNamesResponse)(nil), // 17: server.GetAllSavedDataNamesResponse
	(*DelRequest)(nil),                   // 18: server.DelRequest
}
var file_proto_goph_keeper_proto_depIdxs = []int32{
	1,  // 0: server.GrpcService.CreateUser:input_type -> server.UserRegisterRequest
	2,  // 1: server.GrpcService.LoginUser:input_type -> server.UserAuthorizedRequest
	4,  // 2: server.GrpcService.SaveRawData:input_type -> server.SaveRawDataRequest
	5,  // 3: server.GrpcService.SaveLoginWithPassword:input_type -> server.SaveLoginWithPasswordRequest
	6,  // 4: server.GrpcService.SaveBinaryData:input_type -> server.SaveBinaryDataRequest
	7,  // 5: server.GrpcService.SaveCardData:input_type -> server.SaveCardDataRequest
	8,  // 6: server.GrpcService.GetRawData:input_type -> server.GetRawDataRequest
	10, // 7: server.GrpcService.GetLoginWithPassword:input_type -> server.GetLoginWithPasswordRequest
	12, // 8: server.GrpcService.GetBinaryData:input_type -> server.GetBinaryDataRequest
	14, // 9: server.GrpcService.GetCardData:input_type -> server.GetCardDataRequest
	16, // 10: server.GrpcService.GetAllSavedDataNames:input_type -> server.GetAllSavedDataNamesRequest
	18, // 11: server.GrpcService.DelRawData:input_type -> server.DelRequest
	18, // 12: server.GrpcService.DelLoginWithPassword:input_type -> server.DelRequest
	18, // 13: server.GrpcService.DelBinaryData:input_type -> server.DelRequest
	18, // 14: server.GrpcService.DelCardData:input_type -> server.DelRequest
	4,  // 15: server.GrpcService.UpdRawData:input_type -> server.SaveRawDataRequest
	5,  // 16: server.GrpcService.UpdLoginWithPassword:input_type -> server.SaveLoginWithPasswordRequest
	6,  // 17: server.GrpcService.UpdBinaryData:input_type -> server.SaveBinaryDataRequest
	7,  // 18: server.GrpcService.UpdCardData:input_type -> server.SaveCardDataRequest
	3,  // 19: server.GrpcService.CreateUser:output_type -> server.AuthorizedResponse
	3,  // 20: server.GrpcService.LoginUser:output_type -> server.AuthorizedResponse
	0,  // 21: server.GrpcService.SaveRawData:output_type -> server.ErrorResponse
	0,  // 22: server.GrpcService.SaveLoginWithPassword:output_type -> server.ErrorResponse
	0,  // 23: server.GrpcService.SaveBinaryData:output_type -> server.ErrorResponse
	0,  // 24: server.GrpcService.SaveCardData:output_type -> server.ErrorResponse
	9,  // 25: server.GrpcService.GetRawData:output_type -> server.GetRawDataResponse
	11, // 26: server.GrpcService.GetLoginWithPassword:output_type -> server.GetLoginWithPasswordResponse
	13, // 27: server.GrpcService.GetBinaryData:output_type -> server.GetBinaryDataResponse
	15, // 28: server.GrpcService.GetCardData:output_type -> server.GetCardDataResponse
	17, // 29: server.GrpcService.GetAllSavedDataNames:output_type -> server.GetAllSavedDataNamesResponse
	0,  // 30: server.GrpcService.DelRawData:output_type -> server.ErrorResponse
	0,  // 31: server.GrpcService.DelLoginWithPassword:output_type -> server.ErrorResponse
	0,  // 32: server.GrpcService.DelBinaryData:output_type -> server.ErrorResponse
	0,  // 33: server.GrpcService.DelCardData:output_type -> server.ErrorResponse
	0,  // 34: server.GrpcService.UpdRawData:output_type -> server.ErrorResponse
	0,  // 35: server.GrpcService.UpdLoginWithPassword:output_type -> server.ErrorResponse
	0,  // 36: server.GrpcService.UpdBinaryData:output_type -> server.ErrorResponse
	0,  // 37: server.GrpcService.UpdCardData:output_type -> server.ErrorResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_goph_keeper_proto_init() }
func file_proto_goph_keeper_proto_init() {
	if File_proto_goph_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goph_keeper_proto_rawDesc), len(file_proto_goph_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goph_keeper_proto_goTypes,
		DependencyIndexes: file_proto_goph_keeper_proto_depIdxs,
		MessageInfos:      file_proto_goph_keeper_proto_msgTypes,
	}.Build()
	File_proto_goph_keeper_proto = out.File
	file_proto_goph_keeper_proto_goTypes = nil
	file_proto_goph_keeper_proto_depIdxs = nil
}
